ExUnit.start()
# Mox.defmock(ConsulShim.createkvmock, for: ConsulShim.createkv)
# Mox.defmock(ConsulShim.deletekvmock, for: ConsulShim.deletekv)
# Mox.defmock(ConsulShim.updatekvmock, for: ConsulShim.updatekv)
# Mox.defmock(ConsulShim.getkvmock, for: ConsulShim.getkv)
